#Specify the attibute to be used for mapping on the Client authenticator app
  
  #Reference Field to be displayed on authenticator mobile app (Defaults to CL argument provided during gem installation)
  <%= "#{Rails.application.class}" %>.config.twofactor_reference_field = "<%= @reference_field %>"

  #Attribute in the model that holds the secret key generated by the gem
  <%= "#{Rails.application.class}" %>.config.twofactor_secret_attribute = "twofactor_secret"

  #Attribute in the model that holds 2factor enabled/disabled flag
  <%= "#{Rails.application.class}" %>.config.twofactor_flag_attribute = "twofactor_enabled"

  #QR-Code size
  <%= "#{Rails.application.class}" %>.config.twofactor_qrcode_size = 6

  #QR-Code quality
  <%= "#{Rails.application.class}" %>.config.twofactor_qrcode_quality = 'm'

  #Override if you'd like to replace Your application's Name with your choice
  <%= "#{Rails.application.class}" %>.config.twofactor_provider_name = ''