#Model to be used for twofacter authentication
<%= "#{Rails.application.class}::TWOFACTOR_MODEL_NAME = '#{@model_name}'" %>

#Reference Field to be displayed on authenticator mobile app (Defaults to CL argument provided during gem installation)
<%= "#{Rails.application.class}::TWOFACTOR_REFERENCE_FIELD = '#{@reference_field}'" %>

#Attribute in the model that holds the secret key generated by the gem
<%= "#{Rails.application.class}::TWOFACTOR_SECRET_ATTRIBUTE = 'twofactor_secret'" %>

#Attribute in the model that holds 2factor enabled/disabled flag
<%= "#{Rails.application.class}::TWOFACTOR_FLAG_ATTRIBUTE = 'twofactor_enabled'" %>

#QR-Code size
<%= "#{Rails.application.class}::TWOFACTOR_QRCODE_SIZE = 6" %>

#QR-Code quality
<%= "#{Rails.application.class}::TWOFACTOR_QRCODE_QUALITY = 'm'" %>

#Override if you'd like to replace Your application's Name with your choice (This will appear in user's authenticator app for his reference)
<%= "#{Rails.application.class}::TWOFACTOR_PROVIDER_NAME = ''" %>